"""Modelos ORM: deben coincidir con las migraciones de Alembic (lo verifica scripts/quality.sh).

Al cargarlos se registran también la seguridad por fila de cada tabla de empresa (`app/core/row_security.py`),
las particiones de las tablas que crecen sin límite (`app/core/partitions.py`) y la SQL de las migraciones que
los modelos no expresan (`app/core/db_sql.py`): `create_all` (pruebas y quality.sh) deja la base igual que las
migraciones."""

from app.core.database import Base
from app.core.db_sql import register_sql_files
from app.core.partitions import register_partitioned_tables
from app.core.row_security import register_tenant_tables
from app.models.auth_session import AuthSession, RateLimitCounter
from app.models.billing import (
    BillingPlan,
    Charge,
    ChargeLine,
    HeadcountDay,
    Payment,
    PaymentAllocation,
)
from app.models.calendar import CompanyHoliday, EmployeeAbsence, EmployeeWorkday
from app.models.capture_fingerprint import CaptureFingerprint
from app.models.catalog import (
    CatalogAccessory,
    CatalogAntispoofLevel,
    CatalogApiKeyStatus,
    CatalogApiScope,
    CatalogAssignmentState,
    CatalogAttendanceAction,
    CatalogAttendanceEditReason,
    CatalogAttendanceReviewStatus,
    CatalogBillingStatus,
    CatalogBoardState,
    CatalogChargeStatus,
    CatalogCompanyDocumentType,
    CatalogConfidenceLevel,
    CatalogCountry,
    CatalogCurrency,
    CatalogDayOffType,
    CatalogDeviceStatus,
    CatalogDiscountRecurrence,
    CatalogDiscountType,
    CatalogEmployeeDeviceMode,
    CatalogEmployeeDocumentType,
    CatalogEnrollmentFlag,
    CatalogEnrollmentRejectionReason,
    CatalogEnrollmentStatus,
    CatalogErrorSeverity,
    CatalogErrorStatus,
    CatalogFaceError,
    CatalogFaceStatus,
    CatalogFlashMode,
    CatalogFraudCaseEventKind,
    CatalogFraudCaseStatus,
    CatalogFraudKind,
    CatalogLivenessAction,
    CatalogMenuModule,
    CatalogPaymentMethod,
    CatalogPaymentStatus,
    CatalogPolicyChangeStatus,
    CatalogPolicyPreset,
    CatalogPricePeriod,
    CatalogPricingMode,
    CatalogReverificationReason,
    CatalogReviewReason,
    CatalogRiskAction,
    CatalogRiskSignal,
    CatalogRiskTier,
    CatalogRole,
    CatalogScreen,
    CatalogSessionRevocationReason,
    CatalogShiftRequestStatus,
    CatalogSignalMode,
    CatalogSlowAlertStatus,
    CatalogStorageCategory,
    CatalogSuspensionReason,
    CatalogTaxIdType,
    CatalogTranslation,
    CatalogValidatorMode,
    CatalogVerificationMethod,
    CatalogVerificationReason,
    CatalogVoiceProfile,
    CatalogVoiceQuestion,
    CatalogWorkMode,
    CatalogWorkSessionStatus,
    MenuModuleScreen,
    RoleScreen,
    ValidatorModeMethod,
)
from app.models.company import Company
from app.models.company_api_key import CompanyApiKey, CompanyApiKeyScope
from app.models.company_document import CompanyDocument
from app.models.department import Department, DepartmentManager
from app.models.drift import CompanyFraudWeekly, EngineVersion, SignalDrift
from app.models.employee import Employee
from app.models.employee_device import EmployeeDevice
from app.models.employee_document import EmployeeDocument
from app.models.employee_qr import EmployeeQr
from app.models.employee_status_event import EmployeeStatusEvent
from app.models.enrollment_draft import FaceEnrollmentDraft
from app.models.enrollment_voice import EnrollmentVoiceAnswer
from app.models.enums import (
    ApiKeyStatus,
    ApiScope,
    AssignmentState,
    AttendanceAction,
    AttendanceReviewStatus,
    BillingStatus,
    BoardState,
    ChargeStatus,
    Currency,
    DeviceStatus,
    DiscountRecurrence,
    DiscountType,
    EmployeeDeviceMode,
    EnrollmentStatus,
    ErrorSeverity,
    ErrorStatus,
    FaceStatus,
    FlashMode,
    FraudCaseEventKind,
    FraudCaseStatus,
    FraudKind,
    PaymentStatus,
    PerfKind,
    PolicyChangeStatus,
    PolicyPreset,
    PricePeriod,
    PricingMode,
    RiskAction,
    RiskSignal,
    RiskTier,
    Screen,
    SessionRevocationReason,
    ShiftRequestStatus,
    SignalMode,
    SlowAlertStatus,
    StorageCategory,
    SuspensionReason,
    UserRole,
    ValidatorMode,
    VerificationMethod,
    VoiceQuestion,
    WorkMode,
    WorkSessionStatus,
)
from app.models.error_report import ErrorOccurrence, ErrorReport
from app.models.face_challenge import FaceChallenge
from app.models.face_embedding import FaceEmbedding
from app.models.face_enrollment import FaceEnrollment, FaceEnrollmentFlag
from app.models.face_security import FaceAttemptMetric, SecurityThreshold
from app.models.fraud import (
    AttackSignature,
    CaptureTrace,
    FraudCase,
    FraudCaseAttempt,
    FraudCaseEvent,
    FraudEvidence,
    PolicyChange,
    RiskAssessment,
    RiskSignalStat,
)
from app.models.passkey import Passkey, PasskeyChallenge
from app.models.performance import PerfDay, PerfHour, PerfMinute, SlowRequestAlert
from app.models.remembered_account import RememberedAccount
from app.models.shift import Shift, ShiftAssignment, ShiftChangeRequest, ShiftSite, WorkSite
from app.models.site_kiosk import SiteKiosk
from app.models.storage import StorageDeletion, StorageStatus
from app.models.usage import DailyTask, StorageSnapshot, UsageDaily, UsageRoute, UsageUser
from app.models.user import User
from app.models.user_avatar import UserAvatar
from app.models.validator import Validator
from app.models.validator_device import ValidatorDevice
from app.models.validator_status_event import ValidatorStatusEvent
from app.models.verification_log import VerificationLog
from app.models.verification_policy import VerificationPolicy
from app.models.work_session import AttendanceEvent, WorkBreak, WorkSession

__all__ = [
    "ApiKeyStatus",
    "ApiScope",
    "AssignmentState",
    "AttackSignature",
    "AttendanceAction",
    "AttendanceEvent",
    "AttendanceReviewStatus",
    "AuthSession",
    "BillingPlan",
    "BillingStatus",
    "BoardState",
    "CaptureFingerprint",
    "CaptureTrace",
    "CatalogAccessory",
    "CatalogAntispoofLevel",
    "CatalogApiKeyStatus",
    "CatalogApiScope",
    "CatalogAssignmentState",
    "CatalogAttendanceAction",
    "CatalogAttendanceEditReason",
    "CatalogAttendanceReviewStatus",
    "CatalogBillingStatus",
    "CatalogBoardState",
    "CatalogChargeStatus",
    "CatalogCompanyDocumentType",
    "CatalogConfidenceLevel",
    "CatalogCountry",
    "CatalogCurrency",
    "CatalogDayOffType",
    "CatalogDeviceStatus",
    "CatalogDiscountRecurrence",
    "CatalogDiscountType",
    "CatalogEmployeeDeviceMode",
    "CatalogEmployeeDocumentType",
    "CatalogEnrollmentFlag",
    "CatalogEnrollmentRejectionReason",
    "CatalogEnrollmentStatus",
    "CatalogErrorSeverity",
    "CatalogErrorStatus",
    "CatalogFaceError",
    "CatalogFaceStatus",
    "CatalogFlashMode",
    "CatalogFraudCaseEventKind",
    "CatalogFraudCaseStatus",
    "CatalogFraudKind",
    "CatalogLivenessAction",
    "CatalogMenuModule",
    "CatalogPaymentMethod",
    "CatalogPaymentStatus",
    "CatalogPolicyChangeStatus",
    "CatalogPolicyPreset",
    "CatalogPricePeriod",
    "CatalogPricingMode",
    "CatalogReverificationReason",
    "CatalogReviewReason",
    "CatalogRiskAction",
    "CatalogRiskSignal",
    "CatalogRiskTier",
    "CatalogRole",
    "CatalogScreen",
    "CatalogSessionRevocationReason",
    "CatalogShiftRequestStatus",
    "CatalogSignalMode",
    "CatalogSlowAlertStatus",
    "CatalogStorageCategory",
    "CatalogSuspensionReason",
    "CatalogTaxIdType",
    "CatalogTranslation",
    "CatalogValidatorMode",
    "CatalogVerificationMethod",
    "CatalogVerificationReason",
    "CatalogVoiceProfile",
    "CatalogVoiceQuestion",
    "CatalogWorkMode",
    "CatalogWorkSessionStatus",
    "Charge",
    "ChargeLine",
    "ChargeStatus",
    "Company",
    "CompanyApiKey",
    "CompanyApiKeyScope",
    "CompanyDocument",
    "CompanyFraudWeekly",
    "CompanyHoliday",
    "Currency",
    "DailyTask",
    "Department",
    "DepartmentManager",
    "DeviceStatus",
    "DiscountRecurrence",
    "DiscountType",
    "Employee",
    "EmployeeAbsence",
    "EmployeeDevice",
    "EmployeeDeviceMode",
    "EmployeeDocument",
    "EmployeeQr",
    "EmployeeStatusEvent",
    "EmployeeWorkday",
    "EngineVersion",
    "EnrollmentStatus",
    "EnrollmentVoiceAnswer",
    "ErrorOccurrence",
    "ErrorReport",
    "ErrorSeverity",
    "ErrorStatus",
    "FaceAttemptMetric",
    "FaceChallenge",
    "FaceEmbedding",
    "FaceEnrollment",
    "FaceEnrollmentDraft",
    "FaceEnrollmentFlag",
    "FaceStatus",
    "FlashMode",
    "FraudCase",
    "FraudCaseAttempt",
    "FraudCaseEvent",
    "FraudCaseEventKind",
    "FraudCaseStatus",
    "FraudEvidence",
    "FraudKind",
    "HeadcountDay",
    "MenuModuleScreen",
    "Passkey",
    "PasskeyChallenge",
    "Payment",
    "PaymentAllocation",
    "PaymentStatus",
    "PerfDay",
    "PerfHour",
    "PerfKind",
    "PerfMinute",
    "PolicyChange",
    "PolicyChangeStatus",
    "PolicyPreset",
    "PricePeriod",
    "PricingMode",
    "RateLimitCounter",
    "RememberedAccount",
    "RiskAction",
    "RiskAssessment",
    "RiskSignal",
    "RiskSignalStat",
    "RiskTier",
    "RoleScreen",
    "Screen",
    "SecurityThreshold",
    "SessionRevocationReason",
    "Shift",
    "ShiftAssignment",
    "ShiftChangeRequest",
    "ShiftRequestStatus",
    "ShiftSite",
    "SignalDrift",
    "SignalMode",
    "SiteKiosk",
    "SlowAlertStatus",
    "SlowRequestAlert",
    "StorageCategory",
    "StorageDeletion",
    "StorageSnapshot",
    "StorageStatus",
    "SuspensionReason",
    "UsageDaily",
    "UsageRoute",
    "UsageUser",
    "User",
    "UserAvatar",
    "UserRole",
    "Validator",
    "ValidatorDevice",
    "ValidatorMode",
    "ValidatorModeMethod",
    "ValidatorStatusEvent",
    "VerificationLog",
    "VerificationMethod",
    "VerificationPolicy",
    "VoiceQuestion",
    "WorkBreak",
    "WorkMode",
    "WorkSession",
    "WorkSessionStatus",
    "WorkSite",
]

register_tenant_tables(Base.metadata.tables)
register_partitioned_tables(Base.metadata)
register_sql_files(Base.metadata)
