"""Modelos ORM: deben coincidir con las migraciones de Alembic (lo verifica scripts/quality.sh)."""

from app.models.auth_session import AuthSession, RateLimitCounter
from app.models.calendar import CompanyHoliday, EmployeeAbsence, EmployeeWorkday
from app.models.capture_fingerprint import CaptureFingerprint
from app.models.catalog import (
    CatalogAccessory,
    CatalogAntispoofLevel,
    CatalogApiKeyStatus,
    CatalogApiScope,
    CatalogAssignmentState,
    CatalogAttendanceAction,
    CatalogAttendanceEditReason,
    CatalogBoardState,
    CatalogConfidenceLevel,
    CatalogCountry,
    CatalogDayOffType,
    CatalogDeviceStatus,
    CatalogEnrollmentFlag,
    CatalogEnrollmentRejectionReason,
    CatalogEnrollmentStatus,
    CatalogErrorSeverity,
    CatalogErrorStatus,
    CatalogFaceError,
    CatalogFaceStatus,
    CatalogFlashMode,
    CatalogLivenessAction,
    CatalogMenuModule,
    CatalogReverificationReason,
    CatalogRole,
    CatalogScreen,
    CatalogSessionRevocationReason,
    CatalogShiftRequestStatus,
    CatalogValidatorMode,
    CatalogVerificationMethod,
    CatalogVerificationReason,
    CatalogWorkMode,
    CatalogWorkSessionStatus,
    MenuModuleScreen,
    RoleScreen,
    ValidatorModeMethod,
)
from app.models.company import Company
from app.models.company_api_key import CompanyApiKey, CompanyApiKeyScope
from app.models.department import Department, DepartmentManager
from app.models.employee import Employee
from app.models.employee_qr import EmployeeQr
from app.models.enums import (
    ApiKeyStatus,
    ApiScope,
    AssignmentState,
    AttendanceAction,
    BoardState,
    DeviceStatus,
    EnrollmentStatus,
    ErrorSeverity,
    ErrorStatus,
    FaceStatus,
    FlashMode,
    Screen,
    SessionRevocationReason,
    ShiftRequestStatus,
    UserRole,
    ValidatorMode,
    VerificationMethod,
    WorkMode,
    WorkSessionStatus,
)
from app.models.error_report import ErrorOccurrence, ErrorReport
from app.models.face_challenge import FaceChallenge
from app.models.face_embedding import FaceEmbedding
from app.models.face_enrollment import FaceEnrollment, FaceEnrollmentFlag
from app.models.face_security import FaceAttemptMetric, SecurityThreshold
from app.models.remembered_account import RememberedAccount
from app.models.shift import Shift, ShiftAssignment, ShiftAssignmentSite, ShiftChangeRequest, WorkSite
from app.models.user import User
from app.models.validator import Validator
from app.models.validator_device import ValidatorDevice
from app.models.verification_log import VerificationLog
from app.models.verification_policy import VerificationPolicy
from app.models.work_session import AttendanceEvent, WorkBreak, WorkSession

__all__ = [
    "ApiKeyStatus",
    "ApiScope",
    "AssignmentState",
    "AttendanceAction",
    "AttendanceEvent",
    "AuthSession",
    "BoardState",
    "CaptureFingerprint",
    "CatalogAccessory",
    "CatalogAntispoofLevel",
    "CatalogApiKeyStatus",
    "CatalogApiScope",
    "CatalogAssignmentState",
    "CatalogAttendanceAction",
    "CatalogAttendanceEditReason",
    "CatalogBoardState",
    "CatalogConfidenceLevel",
    "CatalogCountry",
    "CatalogDayOffType",
    "CatalogDeviceStatus",
    "CatalogEnrollmentFlag",
    "CatalogEnrollmentRejectionReason",
    "CatalogEnrollmentStatus",
    "CatalogErrorSeverity",
    "CatalogErrorStatus",
    "CatalogFaceError",
    "CatalogFaceStatus",
    "CatalogFlashMode",
    "CatalogLivenessAction",
    "CatalogMenuModule",
    "CatalogReverificationReason",
    "CatalogRole",
    "CatalogScreen",
    "CatalogSessionRevocationReason",
    "CatalogShiftRequestStatus",
    "CatalogValidatorMode",
    "CatalogVerificationMethod",
    "CatalogVerificationReason",
    "CatalogWorkMode",
    "CatalogWorkSessionStatus",
    "Company",
    "CompanyApiKey",
    "CompanyApiKeyScope",
    "CompanyHoliday",
    "Department",
    "DepartmentManager",
    "DeviceStatus",
    "Employee",
    "EmployeeAbsence",
    "EmployeeQr",
    "EmployeeWorkday",
    "EnrollmentStatus",
    "ErrorOccurrence",
    "ErrorReport",
    "ErrorSeverity",
    "ErrorStatus",
    "FaceAttemptMetric",
    "FaceChallenge",
    "FaceEmbedding",
    "FaceEnrollment",
    "FaceEnrollmentFlag",
    "FaceStatus",
    "FlashMode",
    "MenuModuleScreen",
    "RateLimitCounter",
    "RememberedAccount",
    "RoleScreen",
    "Screen",
    "SecurityThreshold",
    "SessionRevocationReason",
    "Shift",
    "ShiftAssignment",
    "ShiftAssignmentSite",
    "ShiftChangeRequest",
    "ShiftRequestStatus",
    "User",
    "UserRole",
    "Validator",
    "ValidatorDevice",
    "ValidatorMode",
    "ValidatorModeMethod",
    "VerificationLog",
    "VerificationMethod",
    "VerificationPolicy",
    "WorkBreak",
    "WorkMode",
    "WorkSession",
    "WorkSessionStatus",
    "WorkSite",
]
